# permissions for end users to view installers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: installer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: krateo-installer
    app.kubernetes.io/part-of: krateo-installer
    app.kubernetes.io/managed-by: kustomize
  name: installer-viewer-role
rules:
- apiGroups:
  - installer.krateo.io
  resources:
  - installers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - installer.krateo.io
  resources:
  - installers/status
  verbs:
  - get
