apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: manager-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: krateo-installer
    app.kubernetes.io/part-of: krateo-installer
    app.kubernetes.io/managed-by: kustomize
  name: manager-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - core.krateo.io
  resources:
  - compositiondefinitions
  - compositiondefinitions/status
  verbs:
  - '*'
- apiGroups:
  - composition.krateo.io
  resources:
  - installers
  - installers/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterroles/status
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterroles/status
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterroles/status
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterrolebindings/status
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterrolebindings/status
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterrolebindings/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - configmaps/status
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/status
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  - horizontalpodautoscalers/status
  verbs:
  - '*'
- apiGroups:
  - krateo.io
  resources:
  - krateoplatformops
  - krateoplatformops/status
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - roles/status
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - rolebindings/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - serviceaccounts/status
  verbs:
  - '*'
- apiGroups:
  - krateo.io
  resources:
  - krateoplatformops
  - krateoplatformops/status
  verbs:
  - '*'
